# encoding: utf-8

require 'bundler/setup'
require 'jara'


task :clean do
  FileUtils.rm_rf('build')
end

namespace :package do
  %w[production staging].each do |environment|
    task(environment) do
      build_command = lambda do
        FileUtils.touch('lib/generated_file.rb')
      end
      releaser = Jara::Releaser.new(environment, nil, build_command: build_command)
      releaser.build_artifact
    end
  end

  task 'test' do
    releaser = Jara::Releaser.new(nil, nil)
    releaser.build_artifact
  end
end
