# encoding: utf-8

require 'bundler/setup'
require 'jara'


task :clean do
  FileUtils.rm_rf('build')
end

namespace :package do
  %w[production staging test].each do |environment|
    task(environment) do
      releaser = Jara::Releaser.new(environment)
      releaser.build_artifact
    end
  end
end
